name: Compile Examples

on:
  push:
  pull_request:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout script repository
        uses: actions/checkout@v4
        with:
            repository: Lesords/actions
            path: ci

      - name: Setup arduino cli
        uses: arduino/setup-arduino-cli@v2.0.0

      - name: Create a ignore.list file
        run: |
          # eg: echo "<path>,<fqbn>" >> ignore.list
          echo "TH02_demo,Seeeduino:nrf52:XIAONRF52840 esp32:ESP32:XIAO_ESP32C3" >> ignore.list
          echo "TH06_demo,Seeeduino:nrf52:XIAOnRF52840" >> ignore.list
          echo "TH06_demo,esp32:esp32:XIAO_esp32C3" >> ignore.list

      - name: Build sketch
        run: ./ci/tools/compile.sh

      - name: Build result
        run: cat build.log

      - name: Generate issue
        if: ${{ env.GITHUB_EVENT_NAME != 'pull_request' }}
        run: ./ci/tools/issue.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
