name: Compile Sketch

# The workflow will run on every push and pull request to the repository
on:
  - push
  - pull_request

jobs:
  compile-sketch:
    runs-on: ubuntu-latest

    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout script repository
        uses: actions/checkout@v4
        with:
            repository: Lesords/actions
            path: ci

      - name: Setup arduino cli
        uses: arduino/setup-arduino-cli@v2.0.0

      - name: Create a ignore.list file
        run: |
          echo "TH02_demo,Seeeduino:nrf52:XIAONRF52840 esp32:ESP32:XIAO_ESP32C3" >> ignore.list
          echo "TH06_demo,Seeeduino:nrf52:XIAOnRF52840" >> ignore.list
          echo "TH06_demo,esp32:esp32:XIAO_esp32C3" >> ignore.list

      - name: Build sketch
        run: ./ci/tools/compile.sh
