name: Compile Sketch

# The workflow will run on every push and pull request to the repository
on:
  - push
  - pull_request

jobs:
  compile-sketch:
    runs-on: ubuntu-latest

    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup arduino cli
        uses: arduino/setup-arduino-cli@v2.0.0

      - name: Build sketch
        run: ./tools/compile.sh
