name: Compile Sketch

# The workflow will run on every push and pull request to the repository
on:
  - push
  - pull_request

jobs:
  compile-sketch:
    runs-on: ubuntu-latest

    steps:
      - name: debug
        run: |
          pwd
          echo "hello world"

      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: debug
        run: |
          pwd
          ls . -al
          ls  /home/runner/work/Grove_Temper_Humidity/Grove_Temper_Humidity -al
          # ls  /home/runner/Arduino/libraries/Grove_Temper_Humidity/ -al

      # For more information: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          # The default is to compile for the Arduino Uno board. If you want to compile for other boards, use the `fqbn` input.
          sketch-paths: |
            # Configure the action to search all folders under the root of the repository for sketches and compile them.
            # This is formatted as a YAML list, which makes it possible to have multiple sketch paths if needed.
            - examples
          libraries: |
              - source-path: /home/runner/work/Grove_Temper_Humidity/Grove_Temper_Humidity
              - name: Grove Temper Humidity TH02
